CREATE TABLE IF NOT EXISTS author (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  name TEXT NOT NULL,
  date TEXT NOT NULL,
  location TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS quotes (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  text TEXT NOT NULL,
  author_id INTEGER NOT NULL,
  FOREIGN KEY (author_id) REFERENCES author(id)
);

CREATE TABLE IF NOT EXISTS tags (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  tag TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS quotes_tags (
  quotes_id INTEGER NOT NULL,
  tags_id INTEGER NOT NULL,
  PRIMARY KEY (quotes_id, tags_id)
);
