CREATE TABLE IF NOT EXISTS quotes (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  text TEXT NOT NULL, author TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tags (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  tag TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS quotes_tags (
  quotes_id INTEGER NOT NULL,
  tags_id INTEGER NOT NULL,
  PRIMARY KEY (quotes_id, tags_id)
);
